### ISSUE TITLE
21/8/2022 Issues

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/easier#1]
- [x] `Upper SuperScript` function is not working properly
![image](https://user-images.githubusercontent.com/86353526/185775551-5c17df30-2722-42c1-9afc-12d3fe14f755.png)
- [x] Extension is still not working on some websites _(Github, facebook,...)_
![image](https://user-images.githubusercontent.com/86353526/185775776-436c49c9-71ec-4d86-8114-68f007862530.png)

**Comment by longtoZ** [comment]
- `Subscript and Superscript` fixed
-  **EASIER** still works well in Github, Facebook,...
![image](https://user-images.githubusercontent.com/67490989/185878891-7e62ff48-cc7d-4a9d-b84e-3a6d522647a6.png)
![image](https://user-images.githubusercontent.com/67490989/185879052-c75c18b4-f236-4d25-b7c9-7573b9f218f4.png)
